# .github/labeler.yml

# Label for bug-related changes
bug:
  - title: /bug/i
  - body: /fix/i
documentation:
  - title: /docs/i
  - body: /documentation/i
enhancement:
  - title: /feature/i
  - body: /enhancement/i

  
