name: Deploy job

on:
  pull_request:
        branches:
          - main
  workflow_run:
    workflows: ["Build and Test"]  # Upstream workflow name
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
            echo "Deploying application..."
            echo "Deployed to the production sucessfully"
