name: Feature Branch build Test

on:
  pull_request:
    branches:
      - Developement

jobs:
  run-build-and-test:
    uses: ./.github/workflows/Feature-branch_codecheck.yml
    with:
      branch: ${{ github.ref_name }}
