name: Auto-Labelling of Issues


on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Adding Labels
        uses: kshvmdn/labeler@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
