name: Run Single Unit Test

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - 'feat*'  # Run on pushes to the feature branch
 
jobs:
  run-single-unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install pytest flake8 # Or other dependencies for your tests

    - name: Run Single Unit Test
      run: |
          export PYTHONPATH=testing
          export PYTHONPATH=scripts
          pytest -k "testing"
